---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-31-22:08:51
---

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.Room.Model.RoomModel : Game.Core.Ioc.BaseModel
---@field roomService Game.Modules.Room.Service.RoomService
---@field room Game.Modules.Room.Vo.RoomVo
---@field roomId number @房间id
---@field myRoomRoleInfo Game.Modules.Room.Vo.RoomRoleVo 房间角色
local RoomModel = class("RoomModel",BaseModel)

function RoomModel:Ctor()

end

return RoomModel
