---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-31-22:08:51
---

---@class RoomRole
---@field roleId string
---@field roleName string
---@field sex number
---@field headIcon number
---@field roomRoleState string

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.Room.Model.RoomModel : Game.Core.Ioc.BaseModel
---@field roomService Game.Modules.Room.Service.RoomService
---@field roomRoleList table<number,RoomRole>
local RoomModel = class("RoomModel",BaseModel)

function RoomModel:Ctor()
    
end

return RoomModel
