---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/3/12 0:05
---

local LuaMonoBehaviour = require("Betel.LuaMonoBehaviour")
---@class Game.Modules.Common.View.Card : Betel.LuaMonoBehaviour
---@field public New function<obj:UnityEngine.GameObject,data:Game.Modules.Room.Vo.CardVo>
---@field public data Game.Modules.Room.Vo.CardVo
local Card = class("Card",LuaMonoBehaviour)

function Card:Ctor(gameObject, data)
    Card.super.Ctor(self, gameObject)
    self.data = data

    self.gameObject:SetActive(true)
    self.transform.localPosition = Vector3.zero
    self.transform.localEulerAngles = Vector3.zero
    self.transform.localScale = Vector3.one

    self.front = self.gameObject:FindChild("CardFront")

    local mr = self.front:GetComponent(typeof(UnityEngine.MeshRenderer)) ---@type UnityEngine.MeshRenderer
    local suit = string.lower(self.data.suit)
    mr.material:SetTexture("_MainTex", Res.LoadTexture(string.format("Atlas/Cards/%s_of_%ss.png",self.data.faceValue,suit)))
end

return Card