---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/15 0:09
---

local LuaMonoBehaviour = require("Betel.LuaMonoBehaviour")
---@class Game.Modules.Common.View.UIView : Betel.LuaMonoBehaviour
---@field public New function<prefab:string | UnityEngine.GameObject, parent:UnityEngine.Transform>
---@field public gameObject UnityEngine.GameObject
---@field public scene Game.Modules.World.Scenes.BaseScene
local UIView = class("UIView",LuaMonoBehaviour)

function UIView:Ctor(prefab,parent)
    UIView.super.Ctor(self)
    self.scene = World.ins.currScene
    if type(prefab) == TYPE.string then
        local prefabObj = Res.LoadPrefab(prefab)
        self.gameObject = Instantiate(prefabObj,parent)
    elseif type(prefab) == TYPE.userdata then --gameObject
        self.gameObject = prefab
        if parent then
            self.gameObject.transform:SetParent(parent)
        else
            logError("UIView 's parent can not nil")
        end
    end
    self.gameObject.transform.localPosition = Vector3.zero
    self.gameObject.transform.localEulerAngles = Vector3.zero
    self.gameObject.transform.localScale = Vector3.one
end

return UIView