---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/19 0:21
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Login.View.ServerItem: Betel.UI.ListItemRenderer
local ServerItem = class("Game.Modules.Login.View.ServerItem",ListItemRenderer)

---@param gameObject UnityEngine.GameObject
function ServerItem:Ctor(gameObject)
    ServerItem.super.Ctor(self,gameObject)
end

function ServerItem:Update(data,index)
    local itemObj = self.gameObject
    self.gameObject:SetText("Text", (index + 1).."服 " .. data.name)
    self.gameObject:SetText("Toggle/Label", data.host..":"..data.port)
    LuaHelper.AddButtonClick(itemObj,handler(self,function ()
        log(string.format("nmgr:Connect(%s, tonumber(%s)",data.host,data.port))
        --nmgr:Connect(data.host, tonumber(data.port),
        --        handler(self,self.onConnectSuccess),
        --        handler(self,self.onConnectFail))
    end))
end

function ServerItem:OnDestroy()

end

return ServerItem