---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-14-01:10:21
---


local CardEvent = require("Game.Modules.Common.Events.CardEvent")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.HongJian.View.HongJianConsoleMdr : Game.Core.Ioc.BaseMediator
---@field hongJianModel Game.Modules.HongJian.Model.HongJianModel
---@field hongJianService Game.Modules.HongJian.Service.HongJianService
local HongJianConsoleMdr = class("HongJianConsoleMdr",BaseMediator)

function HongJianConsoleMdr:OnInit()
    self.selectCardList = List.New()
end

function HongJianConsoleMdr:RegisterListeners()
    self:AddGlobalEventListener(CardEvent.Click, self.OnCardClick)
end

---@param card Game.Modules.Common.View.Card
function HongJianConsoleMdr:OnCardClick(card)
    if card.isSelected then
        self.selectCardList:Add(card)
    else
        self.selectCardList:Remove(card)
    end
end

function HongJianConsoleMdr:On_Click_BtnOperate()
    local str = ""
    for i = 1, self.selectCardList:Size() do
        str = str .. self.selectCardList[i].data:ToString()
    end
    print(str)
end

return HongJianConsoleMdr
