---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-14-01:10:21
---

local HongJianCardExtract = require("Game.Config.Card.Extracts.HongJianCardExtract")
local CardExtract = require("Game.Config.Card.Extracts.CardExtract")
local CardEvent = require("Game.Modules.Common.Events.CardEvent")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.HongJian.View.HongJianConsoleMdr : Game.Core.Ioc.BaseMediator
---@field hongJianModel Game.Modules.HongJian.Model.HongJianModel
---@field hongJianService Game.Modules.HongJian.Service.HongJianService
---@field selectCardList table<number, Game.Config.Card.CardBaseVo>
local HongJianConsoleMdr = class("HongJianConsoleMdr",BaseMediator)

function HongJianConsoleMdr:OnInit()
    self.selectCardItemList = List.New()
    self.selectCardList = List.New()

    self.btnOperate = self.gameObject:FindChild("BtnOperate")
    self.btnSmart = self.gameObject:FindChild("BtnSmart")
    self.btnRule = self.gameObject:FindChild("BtnRule")
    self.btnOperate:SetActive(false)
end

function HongJianConsoleMdr:RegisterListeners()
    self:AddGlobalEventListener(CardEvent.Click, self.OnCardClick)
end

---@param card Game.Modules.Common.View.Card
function HongJianConsoleMdr:OnCardClick(card)
    if card.isSelected then
        self.selectCardItemList:Add(card)
        self.selectCardList:Add(card.data)
    else
        self.selectCardItemList:Remove(card)
        self.selectCardList:Remove(card.data)
    end

    self.btnOperate:SetActive(self.selectCardList:Size() > 0)
    if self.selectCardList:Size() > 0 then

    end
end

--计算牌型
function HongJianConsoleMdr:On_Click_BtnRule()
    if self.selectCardList:Size() > 0  then
        local ce = HongJianCardExtract.New(self.selectCardList._array)
        local group = ce:GetCardGroup()
        print("GetCardGroup : " .. group:ToString())
    end
end

--智能排序
function HongJianConsoleMdr:On_Click_BtnSmart()

end

--取消所有选择牌型
function HongJianConsoleMdr:On_Click_BtnCancelSelect()
    edp:Dispatcher(CardEvent.CancelAllSelect)
end

--提示牌型
function HongJianConsoleMdr:On_Click_BtnPointOut()

end

function HongJianConsoleMdr:On_Click_BtnOperate()
    local str = ""
    for i = 1, self.selectCardList:Size() do
        str = str .. self.selectCardList[i]:ToString()
    end
    print(str)
end

return HongJianConsoleMdr
