---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-11-22:56:14
---

local CardSlot = require("Game.Modules.Common.Utils.CardSlot")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.HongJian.View.HongJianSceneMdr : Game.Core.Ioc.BaseMediator
---@field hongJianModel Game.Modules.HongJian.Model.HongJianModel
---@field hongJianService Game.Modules.HongJian.Service.HongJianService
local HongJianSceneMdr = class("HongJianSceneMdr",BaseMediator)

--桌子的位置(相对玩家,上北下南,左西右东)
local DeskPos = {}
DeskPos.South = "South"
DeskPos.North = "North"
DeskPos.West = "West"
DeskPos.Ease = "Ease"

function HongJianSceneMdr:OnInit()
    self.posSlot = {}

    self.posSlot[DeskPos.South] = self:CreateCardSlot(DeskPos.South,self.hongJianModel.cards,true)
end

function HongJianSceneMdr:CreateCardSlot(pos, cards, showFront)
    local deskPos = GameObject.Find(pos)
    local slot = CardSlot.New(deskPos, cards, showFront)
    return slot
end

return HongJianSceneMdr
