---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/19 18:18
---

---@class Game.Core.Ioc.BaseVo : Betel.LuaObject
local LuaObject = require('Betel.LuaObject')
local BaseVo = class("BaseVo",LuaObject)

function BaseVo:Ctor()

end

return BaseVo