---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/7/13 1:28
--- 全局常量
---

---@class UILayer
UILayer = {}
UILayer.scene = "scene"
UILayer.bg = "bg"
UILayer.bottom = "bottom"
UILayer.depth = "depth"
UILayer.alert = "alert"
UILayer.guide = "guide"
UILayer.top = "top"

ServerName = {}
ServerName.AccountServer = "AccountServer"
ServerName.GateServer = "GateServer"
ServerName.GameServer = "GameServer"

--目标帧率
FrameRate = Application.targetFrameRate
--目标帧间隔时间
FrameTime = 1 / FrameRate

GameName =
{
    Hong_Jian = "Hong_Jian"
}

GameMode =
{
    Hong_Jian = "1vs1"
}
---@class RoomRoleState 玩家在房间中的状态
RoomRoleState =
{
    UnReady         = "UnReady",
    Ready           = "Ready",
    Loading         = "Loading",
    LoadComplete    = "LoadComplete",
    Offline         = "Offline",
    Reconnect       = "Reconnect",
    PlayingGame     = "PlayingGame",
    Automatic       = "Automatic"
}
CardSuit =
{
    None        = "None",       --大王小王没有花色
    Diamond     = "Diamond",    -- ♦
    Club        = "Club",       -- ♣
    Heart       = "Heart",      -- ♥
    Spade       = "Spade"       -- ♠
}
CardSuitValue =
{
    None        = 0,       --大王小王没有花色
    Diamond     = 1,    -- ♦
    Club        = 2,       -- ♣
    Heart       = 3,      -- ♥
    Spade       = 4       -- ♠
}