---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/7/13 1:28
--- 全局常量
---

---@class UILayer
UILayer = {}
UILayer.scene = "scene"
UILayer.bg = "bg"
UILayer.bottom = "bottom"
UILayer.depth = "depth"
UILayer.alert = "alert"
UILayer.guide = "guide"
UILayer.top = "top"

ServerName = {}
ServerName.AccountServer = "AccountServer"
ServerName.GateServer = "GateServer"
ServerName.GameServer = "GameServer"

GameName =
{
    Hong_Jian = "Hong_Jian"
}
