---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/10 0:17
---

LoginAction = {}

LoginAction.LoginAccount = { server = "AccountServer", action = "account@account_login", fields = "username,password" }

LoginAction.LoginRegister = { server = "AccountServer", action = "account@account_register", fields = "username,password" }

LoginAction.LoginGameServer = { server = "GameServer", action = "Player@login_game_server", data = "%s&%s" }

LoginAction.PlayerInfo = "push@player_info"

LoginAction.FetchRandomName = { server = "GameServer", action = "Role@role_random_name", data = "" }

LoginAction.CreateRole = { server = "GameServer", action = "Role@role_create", data = "%s" }

LoginAction.SelectRoleEnterGame = { server = "GameServer", action = "Role@select_role_enter_game", data = "%d" }

RoleAction = {}

RoleAction.RoleInfo = "push@role_info"