---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/10 0:17
---

Action = {}

Action.LoginAccount = { server = "AccountServer", action = "account@account_login", fields = "username,password" }

Action.LoginRegister = { server = "AccountServer", action = "account@account_register", fields = "username,password" }

Action.LoginLobbyServer = { server = "LobbyServer", action = "player@player_login", fields = "aid,token"}

Action.FetchRandomName = { server = "LobbyServer", action = "role@role_random_name", fields = "playerId"}

Action.CreateRole = { server = "LobbyServer", action = "role@role_create", fields = "playerId,roleName"}

Action.EnterGame = { server = "LobbyServer", action = "role@role_enter_game", fields = "playerId" }

Action.JoinMatch = { server = "LobbyServer", action = "match@join_match", fields = "roleId,game,gameMode" }

Action.RoomCreate = "push@create_room"