---
--- Generated by Tools
--- Created by ruizhan911.
--- DateTime: 2019-02-05-23:16:46
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Room.View.Room_HJSceneMdr : Game.Core.Ioc.BaseMediator
---@field roomModel Game.Modules.Room.Model.RoomModel
---@field roomService Game.Modules.Room.Service.RoomService
local Room_HJSceneMdr = class("Room_HJSceneMdr",BaseMediator)

function Room_HJSceneMdr:OnInit()
    
end

return Room_HJSceneMdr
