---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-31-22:08:22
---

local SimpleRoleItem = require("Game.Modules.Room.View.SimpleRoleItem")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Room.View.SampleRoomMdr : Game.Core.Ioc.BaseMediator
---@field roomModel Game.Modules.Room.Model.RoomModel
---@field roomService Game.Modules.Room.Service.RoomService
local SampleRoomMdr = class("SampleRoomMdr",BaseMediator)

function SampleRoomMdr:OnInit()
    self:InitRoleList()
end

function SampleRoomMdr:RegisterListeners()
    nmgr:AddPush(Action.PushEnterRoom, handler(self,self.OnPushEnterRoom))
end

function SampleRoomMdr:OnPushEnterRoom(data)
    self:InitRoleList()
end

function SampleRoomMdr:InitRoleList()
    self.roleList = BaseList.New(self.gameObject:FindChild("ListView"),SimpleRoleItem)
    self.roleList:SetData(self.roomModel.roomRoleList)
end

function SampleRoomMdr:On_Click_BtnStart()
    vmgr:UnloadView(ViewConfig.SampleRoom)
end

return SampleRoomMdr
