---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/31 23:11
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Room.View.SimpleRoleItem: Betel.UI.ListItemRenderer
local SimpleRoleItem = class("Game.Modules.Room.View.SimpleRoleItem",ListItemRenderer)

local headIconUrl = "Textures/HeadIcon/%s.jpg"
---@param gameObject UnityEngine.GameObject
function SimpleRoleItem:Ctor(gameObject)
    SimpleRoleItem.super.Ctor(self,gameObject)
end

---@param data RoomRole
function SimpleRoleItem:Update(data, index)
    self.gameObject:SetText("Text", data.roleName)
    self.gameObject:SetSprite("Icon",Res.LoadSprite(string.format(headIconUrl,tostring(data.headIcon))))
end

function SimpleRoleItem:OnDestroy()

end

return SimpleRoleItem