---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/31 23:11
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Room.View.SimpleRoleItem: Betel.UI.ListItemRenderer
local SimpleRoleItem = class("Game.Modules.Room.View.SimpleRoleItem",ListItemRenderer)

local headIconUrl = "Textures/HeadIcon/%s.jpg"
---@param gameObject UnityEngine.GameObject
function SimpleRoleItem:Ctor(gameObject)
    SimpleRoleItem.super.Ctor(self,gameObject)
end

---@param data RoomRoleVo
function SimpleRoleItem:Update(data, index)
    if data then
        self.gameObject:SetText("Text", data.roleName)
        self.gameObject:SetText("State", data.roleState)
        self.gameObject:SetSprite("Icon",Res.LoadSprite(string.format(headIconUrl,tostring(data.headIcon))))
    else
        self.gameObject:SetText("Text", "<N/A>")
        self.gameObject:SetText("State", "<N/A>")
        self.gameObject:SetSpriteAlpha("Icon", 0)
    end
end

function SimpleRoleItem:OnDestroy()

end

return SimpleRoleItem