---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-27-00:43:04
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Lobby.View.LobbySceneMdr : Game.Core.Ioc.BaseMediator
---@class lobbySceneModel
---@class lobbySceneService
local LobbySceneMdr = class("LobbySceneMdr",BaseMediator)

function LobbySceneMdr:OnInit()
    
end

return LobbySceneMdr
