---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-28-23:33:46
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Lobby.View.LobbyMainMenuMdr : Game.Core.Ioc.BaseMediator
---@field lobbyModel Game.Modules.Lobby.Model.LobbyModel
---@field lobbyService Game.Modules.Lobby.Service.LobbyService
---@field roleModel Game.Modules.Role.Model.RoleModel
local LobbyMainMenuMdr = class("LobbyMainMenuMdr",BaseMediator)

function LobbyMainMenuMdr:OnInit()
    
end

function LobbyMainMenuMdr:On_Click_BtnMatch()
    self.lobbyService:JoinMatch(GameName.Hong_Jian,"1vs1",function ()
        --log("正在匹配")
    end,function ()
        --log("匹配失败")
    end)
end

return LobbyMainMenuMdr
