---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-05-22:38:39
---

local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Robot.Service.RobotService : Game.Core.Ioc.BaseService
---@field robotModel Game.Modules.Robot.Model.RobotModel
---@field roomModel Game.Modules.Room.Model.RoomModel
local RobotService = class("RobotService",BaseService)

function RobotService:Ctor()
    nmgr:AddPush(Action.PushEnterRoom, handler(self,self.OnPushEnterRoom))
    nmgr:AddPush(Action.PushRoomRoleState, handler(self,self.OnPushRoomRoleState))
end

function RobotService:OnPushEnterRoom(response)
    local robotClient = self.robotModel.robotClientMap[response.data.clientRoleId]
    if robotClient then
        local robotOtherClient = self.robotModel.robotClientMap[response.data.id]
        robotClient.room.roleList[response.data.roomPos + 1] = robotOtherClient
    end
end

function RobotService:OnPushRoomRoleState(response)
    local robotClient = self.robotModel.robotClientMap[response.data.clientRoleId]
    if robotClient then
        robotClient.room:UpdateState(response.data.roomPos + 1,response.data.roleState)
    end
end

function RobotService:EnterRoom(roleId, pos)
    self:JsonRequest(Action.EnterRoom, {roleId, self.roomModel.room.id, pos, true})
end

function RobotService:ExitRoom(roleId, pos)
    self:JsonRequest(Action.ExitRoom, {roleId,self.roomModel.room.id, pos, true})
end

function RobotService:ChangeState(roleId, state)
    self:JsonRequest(Action.ChangeState, {self.roomModel.room.id,roleId,state})
end

return RobotService
