---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-14-00:07:19
---


local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Role.Service.RoleService : Game.Core.Ioc.BaseService
local RoleService = class("RoleService",BaseService)
local RoleVo = require("Game.Modules.Role.Vo.RoleVo")

function RoleService:Ctor()
    --nmgr:AddPush(Action.RoleInfo, handler(self,self.OnRoleInfo))
end

---push
function RoleService:OnRoleInfo(response)
    log("角色进入游戏:"..response.roleInfo.roleName)
    --self.roleModel.mainRoleInfo = RoleVo.New(response.roleInfo)
end

return RoleService
