---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-14-00:07:17
---

---@class Game.Modules.Role.Model.RoleModel : Game.Core.Ioc.BaseModel
local BaseModel = require("Game.Core.Ioc.BaseModel")
local RoleModel = class("RoleModel",BaseModel)

function RoleModel:Ctor()
    self.mainRoleInfo = nil
end

return RoleModel
