---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/3/14 23:05
--- 牌型提取器
---

local CardGroup = require("Game.Config.Card.CardGroup")
local LuaObject = require('Betel.LuaObject')
---@class Game.Config.Card.Extracts.CardExtract : Betel.LuaObject
---@field New function<cards : table<number, Game.Config.Card.CardBaseVo>>
---@field cards table<number, Game.Config.Card.CardBaseVo>
local CardExtract = class("Game.Config.Card.Extracts.CardExtract",LuaObject)

---@param cards table<number, Game.Config.Card.CardBaseVo>
function CardExtract:Ctor()
end

---@param cards table<number, Game.Config.Card.CardBaseVo>
function CardExtract:isSingle(cards)
    if #cards == 1 then
        return true
    else
        return CardGroupType.NONE
    end
end

---@param cards table<number, Game.Config.Card.CardBaseVo>
function CardExtract:isDouble(cards)
    if #cards == 2 and cards[1].faceValue == cards[2].faceValue then
        return true
    else
        return false
    end
end

--是否是顺子
---@param cards table<number, Game.Config.Card.CardBaseVo>
---@param size number 顺子数量
---@param min number 最小连续数量
---@return boolean
function CardExtract:isStraight(cards, size, min)
    local cardNum = #cards
    --数量是否符合
    if cardNum < size * min or cardNum % size ~= 0 then
        return false
    else
        local num = cardNum / size
        for i = 1, num do
            --验证点数是否一样
            for j = 1, size - 1 do
                if cards[j].faceValue ~= cards[j + 1].faceValue then
                    return false
                end
            end
            --验证是否连续
            if Mathf.Abs(cards[(i - 1) * size + 1].faceValue - cards[i * size + 1].faceValue) ~= 1 then
                return false
            end
        end
        return true
    end
end

return CardExtract