---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/3/14 23:59
--- 红尖牌型提取器
---

local CardGroup = require("Game.Config.Card.CardGroup")
local CardExtract = require('Game.Config.Card.Extracts.CardExtract')
---@class Game.Config.Card.Extracts.HongJainCardExtract : Game.Config.Card.Extracts.CardExtract
local HongJainCardExtract = class("Game.Config.Card.Extracts.HongJainCardExtract",CardExtract)

---@param cards table<number, Game.Config.Card.CardBaseVo>
function HongJainCardExtract:Ctor(cards)
    HongJainCardExtract.super.Ctor(cards)
end

function HongJainCardExtract:extract(cards)

end

return HongJainCardExtract