---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-31-22:08:50
---

local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Room.Service.RoomService : Game.Core.Ioc.BaseService
---@field roomModel Game.Modules.Room.Model.RoomModel
local RoomService = class("RoomService",BaseService)

function RoomService:Ctor()
    
end

return RoomService
