---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/3/11 23:06
--- 一手牌 -- 牌的集合
---

local Card = require("Game.Modules.Common.View.Card")
local LuaMonoBehaviour = require("Betel.LuaMonoBehaviour")
---@class Game.Modules.Common.Utils.CardSlot : Betel.LuaMonoBehaviour
---@field public New function<deskPosObj:UnityEngine.GameObject, cards:table<number, Game.Modules.Room.Vo.CardVo>>
---@field public cards table<number, Game.Modules.Room.Vo.CardVo>
---@field public deskPosObj UnityEngine.GameObject
---@field public showFront boolean
---@field public cardList Betel.List
---@field public cardItemList table<number, Game.Modules.Common.View.Card>
local CardSlot = class("CardSlot",LuaMonoBehaviour)

local Gap = 0
local ZRot = -0.001
local CardWidth = 0.038
---@param deskPosObj UnityEngine.GameObject
---@param cards table<number, Game.Modules.Room.Vo.CardVo>
---@param showFront boolean
function CardSlot:Ctor(deskPosObj, cards, showFront)
    self.cards = cards
    self.deskPosObj = deskPosObj
    self.showFront = showFront

    self.cardList = List.New(cards)
    self.cardItemList = List.New()
    self.cardPrefab = Res.LoadPrefab("Prefabs/Scene/Cards/Prefabs/Card.prefab")

    self:CreateCardSlot()
    self:Reposition()
end

function CardSlot:CreateCardSlot()
    for i = 1, #self.cards do
        local card = Card.New(Instantiate(self.cardPrefab,self.deskPosObj.transform), self.cards[i])
        self.cardItemList:Add(card)
    end
end

function CardSlot:Reposition()
    local cardNum = self.cardItemList:Size()
    local startX = -(cardNum * CardWidth + (cardNum - 1) * Gap) / 2 + CardWidth / 2
    for i = 1, self.cardItemList:Size() do
        local card = self.cardItemList[i]
        card.gameObject.transform.localPosition = Vector3.New(startX + (i - 1) * (CardWidth + Gap), 0, 0)
        card.gameObject.transform.localEulerAngles = Vector3.New(0, 0, i * ZRot)
    end
end

return CardSlot