---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/3/14 23:06
--- 牌型
---

local LuaObject = require('Betel.LuaObject')
---@class Game.Config.Card.CardGroup : Betel.LuaObject
---@field New function<cards : table<number, Game.Config.Card.CardBaseVo>>
---@field cards table<number, Game.Config.Card.CardBaseVo>
---@field groupType CardGroupType
local CardGroup = class("Game.Config.Card.CardGroup",LuaObject)

---@param cards table<number, Game.Config.Card.CardBaseVo>
function CardGroup:Ctor(cards)
    self.cards = cards
end

function CardGroup:ToString()
    return self.__cname
end

return CardGroup