---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/20 16:21
---

vmgr = require("Game.Manager.ViewManager").New()
nmgr = require("Game.Manager.NetworkManager").New()

log("All managers has all require")