---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-05-23:59:17
---

local BaseVo = require("Game.Core.BaseVo")
---@class Game.Modules.Room.Vo.CardVo : Game.Core.BaseVo
---@field faceValue number
---@field suit string
local CardVo = class("Game.Modules.Room.Vo.CardVo",BaseVo)

function CardVo:Ctor()
    
end

return CardVo
